### ISSUE TITLE
[crash] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by mcccarthy** [WarningImHack3r/npm-update-dependencies#145] opened 2024-10-04 06:29 UTC
### What is the issue?

removed depracates and crashed

### What are the steps to reproduce this issue?

removed depracates and crashed

### What were you expecting to happen?

removed depracates and crashed

### Paste any relevant logs, error output, etc.

```shell
java.util.ConcurrentModificationException
	at com.github.warningimhack3r.npmupdatedependencies.ui.statusbar.WidgetBar.getSelectedValue(StatusBarFactory.kt:234)
```

### What OS are you experiencing the problem on?

Linux

### Additional platform information

Build version: WebStorm 2024.2.2 Build: #WS-242.22855.79 September 18, 2024
JRE: 21.0.3+13-b509.15, JetBrains s.r.o.
JVM: 21.0.3+13-b509.15, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 6.8.0-45-generic (amd64)

=== Plugins ===
Custom plugins: [NPM Update Dependencies (3.2.1), Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.20.4), Key Promoter X (2024.2.0), .env files support (2024.2.1), Prisma ORM (242.22855.32)]
Disabled plugins:[JetBrains AI Assistant (242.22855.75), Tailwind Formatter (2.0.11), Eclipse Keymap (242.22855.79)]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment] 2024-10-04 07:41
Duplicate of #144

**Comment by WarningImHack3r** [comment] 2024-10-04 07:41
Should be fixed in the next release

**Closed by WarningImHack3r** 2024-10-04 07:41 UTC
Labels: bug
