### ISSUE TITLE
Status bar stuck at gathering registries

### ISSUE THREAD

**Issue by oskarhertzman** [WarningImHack3r/npm-update-dependencies#102] opened 2024-05-08 06:47 UTC
### What is the issue?

when opening a package.json file, the bottom bar just says gathering registries without actually parsing versions etc.

### What are the steps to reproduce this issue?

1. use version 2.3.0 on webstorm 2023.3.6
2. open package.json
3. watch it hang in bottom right of action bar

![image](https://github.com/WarningImHack3r/npm-update-dependencies/assets/43958723/edadfca9-2996-4e76-af81-358b059c56f6)

### What were you expecting to happen?

To successfully list the potential updates for my dependencies.

### What OS are you experiencing the problem on?

macOS

### Additional platform information

MacOS Sonoma 14.4
Webstorm 2023.3.6
NPM Update Dependencies 2.3.0

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment] 2024-05-08 09:54
Hi there, sorry for the inconvenience.

How long did you wait? Can you run `npm config ls` in a terminal and tell me what happens? (Does it output your config correctly? Does it error? Does it require a login/something else?)

**Comment by oskarhertzman** [comment] 2024-05-08 11:14
It happens indefinitely. 

config:
```
; "project" config from /Users/oskar/Documents/projects/dirma/.npmrc

engine-strict = true 

; node bin location = /Users/oskar/.nvm/versions/node/v20.10.0/bin/node
; node version = v20.10.0
; npm local prefix = /Users/oskar/Documents/projects/dirma
; npm version = 10.2.3
; cwd = /Users/oskar/Documents/projects/dirma
; HOME = /Users/oskar
; Run `npm config ls -l` to show all defaults.
```

**Comment by WarningImHack3r** [comment] 2024-05-08 12:10
Alright can you send me the logs of my plugins? You can do so by:
1. Enable my plugin's debug logs by setting the line below in `Help > Diagnostic Tools > Debug Log Settings…`:
  ```
  #com.github.warningimhack3r.npmupdatedependencies
  ```
2. Restart your IDE, wait until your problem occurs and open the `idea.log` file you find by going to `Help > Show Log in Finder`
3. In there, if you can send me the 50-ish lines before the end, I could try to diagnose your issue more precisely!

**Comment by WarningImHack3r** [comment] 2024-05-08 12:12
Btw, I didn’t notice it was you from the reviews and the previous issue here, thanks for your support, sorry for those problems and hi again :)

**Comment by tborychowski** [comment] 2024-05-08 21:04
Hi,
I have the same issue (and a similar setup). Also looks like the process hangs while in "Gathering...". This is what I see in the PHPStorm Activity Monitor:

![2024-05-08 at 22 03 10](https://github.com/WarningImHack3r/npm-update-dependencies/assets/392513/7640c401-a9a2-4b84-a308-284a03d528db)

**Comment by WarningImHack3r** [comment] 2024-05-08 21:36
Hi @tborychowski, can you also give me the result (or at least tell it to me)

> How long did you wait? Can you run `npm config ls` in a terminal and tell me what happens? (Does it output your config correctly? Does it error? Does it require a login/something else?)

Please also give me the log output with the instructions above. Thanks!

**Comment by tborychowski** [comment] 2024-05-08 22:43
here's mine:

- in PHPStorm - I left it running for ~5 min and there was no change
- I can run `npm config ls` in terminal and it's almost instant
- Yes, the config looks correct, no login required

Here's the config:

```npmrc
; "builtin" config from /opt/homebrew/Cellar/node@18/18.20.2/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew"

; "user" config from /Users/tom/.npmrc

//registry.npmjs.org/:_authToken = (protected)
audit = false
fund = false

; node bin location = /opt/homebrew/Cellar/node@18/18.20.2/bin/node
; node version = v18.20.2
; npm local prefix = /Users/tom/projects/project1
; npm version = 10.5.0
; cwd = /Users/tom/projects/project1
; HOME = /Users/tom
; Run `npm config ls -l` to show all defaults.
```

**Comment by WarningImHack3r** [comment] 2024-05-09 08:22
> Thanks for your help! And let me know if you need me to do any more tests :-)

Thank you very much for this detailed information!

> Edit: I checked the `idea.log` (as you described above) and looks like this is the problem:
> 
> ```
> 
> 2024-05-08 23:53:42,611 [   3454]   WARN - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Error while executing "npm config ls"
> java.io.IOException: Cannot run program "npm": error=2, No such file or directory
> ```
> 
> `npm` is definitely available in the terminal and in my `$PATH` and it's in: `/opt/homebrew/bin/npm`

Hmmm this is really weird! I changed absolutely nothing on that side in the recent updates (except adding logs), so it’s really weird if it just started breaking! It also shouldn’t break the workflow and just skip that part and continue…
 
I’ll investigate!

**Comment by WarningImHack3r** [comment] 2024-05-09 11:14
@tborychowski is that log output the last thing happening from my plugin? Can you send me the few lines before and everything after that that's from the plugin?

**Comment by WarningImHack3r** [comment] 2024-05-09 12:19
Alright @oskarhertzman @tborychowski can you try this version? [npm-update-dependencies-2.3.1-beta.1.zip](https://github.com/WarningImHack3r/npm-update-dependencies/files/15262077/npm-update-dependencies-2.3.1-beta.1.zip)
It will fix high CPU usage [Tom noticed in the Activity Monitor](https://github.com/WarningImHack3r/npm-update-dependencies/issues/102#issuecomment-2101462444), and might fix this issue, thanks to a refactored logic. _(it won't fix the `npm not found` issue though, I still have no clue why this happens — it shouldn't be an issue though as the code is made so that this step will be skipped if failing)_

**Comment by tborychowski** [comment] 2024-05-09 12:20
Hi @WarningImHack3r, here's the full log from your app (from clean start of phpstorm to clean exit, with the error happening in the middle):

<details>
    <summary>idea.log</summary>

```log
...
2024-05-09 13:11:34,444 [    389]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level DEBUG is set for the following category: com.github.warningimhack3r.npmupdatedependencies
2024-05-09 13:11:34,444 [    389]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level DEBUG is set for the following category: #com.github.warningimhack3r.npmupdatedependencies
2024-05-09 13:11:34,444 [    389]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level DEBUG is set for the following category: com.github.warningimhack3r.npmupdatedependencies
2024-05-09 13:11:34,445 [    390]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level DEBUG is set for the following category: com.github.warningimhack3r.npmupdatedependencies
2024-05-09 13:11:34,445 [    390]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level DEBUG is set for the following category: #com.github.warningimhack3r.npmupdatedependencies
2024-05-09 13:11:34,445 [    390]   INFO - #c.i.d.l.LogLevelConfigurationManager - Level DEBUG is set for the following category: com.github.warningimhack3r.npmupdatedependencies
...
2024-05-09 13:11:56,595 [  22540]   FINE - #com.github.warningimhack3r.npmupdatedependencies.ui.banner.DeprecationBanner - Leaving: no deprecations found
2024-05-09 13:11:56,845 [  22790]   INFO - #c.i.j.n.p.n.PackageVersionRangeMatcher - Matching 25 done in 177 ms
2024-05-09 13:11:57,096 [  23041]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 2 dist-tags, 36 versions for @eslint/js in 181ms
2024-05-09 13:11:58,344 [  24289]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 120 versions for @perfectthings/ui in 1247ms
2024-05-09 13:11:58,487 [  24432]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 2 dist-tags, 41 versions for @stylistic/eslint-plugin-js in 141ms
2024-05-09 13:11:58,614 [  24559]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 214 versions for apexcharts in 127ms
2024-05-09 13:11:58,711 [  24656]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 27 versions for del in 96ms
2024-05-09 13:11:59,412 [  25357]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 33 versions for esbuild-svelte in 701ms
2024-05-09 13:11:59,545 [  25490]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 3 dist-tags, 357 versions for eslint in 132ms
2024-05-09 13:12:00,228 [  26173]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 22 versions for eslint-formatter-pretty in 682ms
2024-05-09 13:12:00,344 [  26289]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 2 dist-tags, 79 versions for eslint-plugin-svelte in 115ms
2024-05-09 13:12:00,992 [  26937]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 2 dist-tags, 124 versions for favicons in 647ms
2024-05-09 13:12:01,082 [  27027]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 109 versions for globals in 89ms
2024-05-09 13:12:01,169 [  27114]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 67 versions for gulp in 86ms
2024-05-09 13:12:01,275 [  27220]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 56 versions for gulp-clean-css in 104ms
2024-05-09 13:12:01,397 [  27342]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 26 versions for gulp-concat in 121ms
2024-05-09 13:12:02,130 [  28075]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 144 versions for gulp-esbuild in 732ms
2024-05-09 13:12:02,473 [  28418]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 29 versions for gulp-eslint-new in 342ms
2024-05-09 13:12:02,585 [  28530]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 32 versions for gulp-livereload in 111ms
2024-05-09 13:12:03,148 [  29093]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 4 versions for gulp-stylelint-esm in 561ms
2024-05-09 13:12:03,264 [  29209]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 48 versions for open in 113ms
2024-05-09 13:12:03,368 [  29313]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 41 versions for sortablejs in 103ms
2024-05-09 13:12:03,496 [  29441]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 2 dist-tags, 231 versions for stylelint in 127ms
2024-05-09 13:12:03,654 [  29599]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 2 dist-tags, 47 versions for stylelint-config-standard in 157ms
2024-05-09 13:12:04,370 [  30315]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 1 dist-tags, 19 versions for stylelint-formatter-pretty in 715ms
2024-05-09 13:12:04,508 [  30453]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 2 dist-tags, 605 versions for svelte in 137ms
2024-05-09 13:12:04,622 [  30567]   INFO - #c.i.j.n.n.r.NpmRegistryServiceImpl - Found 2 dist-tags, 38 versions for through2 in 113ms
2024-05-09 13:12:04,624 [  30569]   FINE - #com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator - No registries found, scanning for registries...
2024-05-09 13:12:04,626 [  30571]   INFO - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.RegistriesScanner - Starting to scan registries
2024-05-09 13:12:04,627 [  30572]   INFO - #com.github.warningimhack3r.npmupdatedependencies.ui.statusbar.StatusBarHelper - Updating widget
2024-05-09 13:12:04,627 [  30572]   FINE - #com.github.warningimhack3r.npmupdatedependencies.ui.statusbar.StatusBarHelper - Updating widget for project zakupnik5
2024-05-09 13:12:04,628 [  30573]   FINE - #com.github.warningimhack3r.npmupdatedependencies.ui.statusbar.StatusBarHelper - Widget updated for project zakupnik5
2024-05-09 13:12:04,628 [  30573]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Executing "npm config ls"
2024-05-09 13:12:04,661 [  30606]   WARN - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Error while executing "npm config ls"
java.io.IOException: Cannot run program "npm": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner.execute(ShellRunner.kt:21)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.RegistriesScanner.scan(RegistriesScanner.kt:24)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator.doAnnotate(DeprecationAnnotator.kt:43)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator.doAnnotate(DeprecationAnnotator.kt:25)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.lambda$doAnnotate$1(ExternalToolPass.java:208)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:80)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:72)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:206)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:200)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:163)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:268)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:163)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$15(BackgroundTaskUtil.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:161)
	at com.intellij.util.ui.update.ContextAwareUpdate.run$lambda$1$lambda$0(ContextAwareUpdate.kt:49)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.util.ui.update.ContextAwareUpdate.run(ContextAwareUpdate.kt:48)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:354)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:344)
	at com.intellij.util.ui.update.MergingUpdateQueue.doFlush(MergingUpdateQueue.java:301)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:283)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:250)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.util.Alarm$Request.lambda$runSafely$0(Alarm.java:369)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:357)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 57 more
2024-05-09 13:12:04,663 [  30608]   FINE - #com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator - Registries scanned
2024-05-09 13:12:04,663 [  30608]   FINE - #com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator - Waiting for registries and/or updates to be scanned...
...

```
</details>

**Comment by tborychowski** [comment] 2024-05-09 12:28
I'm testing the new version and it's like you said: no high CPU anymore, and it continues after the error. But it gets even weirder :-D
Here's one piece of log:

```
2024-05-09 13:22:48,471 [  29530]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Executing "npm v @stylistic/eslint-plugin-js dist.tarball"
2024-05-09 13:22:48,476 [  29535]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Executing "npm v through2 dist.tarball"
2024-05-09 13:22:48,482 [  29541]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Executing "npm v eslint dist.tarball"
2024-05-09 13:22:48,488 [  29547]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Executing "npm v del dist.tarball"
2024-05-09 13:22:48,494 [  29553]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Executing "npm v @perfectthings/ui dist.tarball"
2024-05-09 13:22:48,500 [  29559]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Executing "npm v apexcharts dist.tarball"
2024-05-09 13:22:48,506 [  29565]   WARN - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Error while executing "npm v eslint dist.tarball"
java.io.IOException: Cannot run program "npm": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner.execute(ShellRunner.kt:21)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient.getRegistry(NPMJSClient.kt:42)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient.getPackageDeprecation(NPMJSClient.kt:144)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator$doAnnotate$2.invokeSuspend(DeprecationAnnotator.kt:69)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator$doAnnotate$2.invoke(DeprecationAnnotator.kt)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.DeprecationAnnotator$doAnnotate$2.invoke(DeprecationAnnotator.kt)
	at com.github.warningimhack3r.npmupdatedependencies.backend.extensions.ExtensionsKt$parallelMap$1$1$1$1.invokeSuspend(Extensions.kt:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 14 more
```

It works for some, ot fails for others...

**Comment by tborychowski** [comment] 2024-05-09 12:30
and weirder:
```
2024-05-09 13:22:49,641 [  30700]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Executing "npm config ls"
2024-05-09 13:22:49,641 [  30700]   FINE - #com.github.warningimhack3r.npmupdatedependencies.ui.statusbar.StatusBarHelper - Widget updated for project zakupnik5
2024-05-09 13:22:49,641 [  30700]   FINE - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Executing "npm config ls"
2024-05-09 13:22:49,656 [  30715]   WARN - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner - Error while executing "npm config ls"
java.io.IOException: Cannot run program "npm": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.ShellRunner.execute(ShellRunner.kt:21)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.RegistriesScanner.scan(RegistriesScanner.kt:25)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient.getRegistry(NPMJSClient.kt:34)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.NPMJSClient.getLatestVersion(NPMJSClient.kt:92)
	at com.github.warningimhack3r.npmupdatedependencies.backend.engine.PackageUpdateChecker.areUpdatesAvailable(PackageUpdateChecker.kt:89)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator$doAnnotate$2.invokeSuspend(UpdatesAnnotator.kt:70)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator$doAnnotate$2.invoke(UpdatesAnnotator.kt)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.UpdatesAnnotator$doAnnotate$2.invoke(UpdatesAnnotator.kt)
	at com.github.warningimhack3r.npmupdatedependencies.backend.extensions.ExtensionsKt$parallelMap$1$1$1$1.invokeSuspend(Extensions.kt:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 16 more
```

**Comment by tborychowski** [comment] 2024-05-09 12:36
No, the statusbar widget still hangs on "Gathering registries...".
What's more - these failures probably affect the popup, as there's no nice docs with links to update, just the small default link:

![2024-05-09 at 13 34 25](https://github.com/WarningImHack3r/npm-update-dependencies/assets/392513/67c81e93-0a68-4200-b57c-6193463ffab9)


Is it possible that jetbrains did something weird to their IDE recently (I remember there was an update recently)?

**Comment by WarningImHack3r** [comment] 2024-05-09 12:39
> No, the statusbar widget still hangs on "Gathering registries...".

Alright, I'll take another look...

> Is it possible that jetbrains did something weird to their IDE recently (I remember there was an update recently)?

That popup is the default thing that's created by the IDE for a few versions now, nothing's wrong here, my plugin adds on top of that when an update is available for that package, alongside the version highlighting.

**Comment by WarningImHack3r** [comment] 2024-05-09 13:37
Here is another build, improving logic yet again (beta 1 led to duplicated config parsing): [npm-update-dependencies-2.3.1-beta.2.zip](https://github.com/WarningImHack3r/npm-update-dependencies/files/15262914/npm-update-dependencies-2.3.1-beta.2.zip)

It should also mitigate failures for `npm not found` because it introduces a retry mechanism (2 retries max, 3 total) for shell commands.

However I still have no clue about the root cause of the `Gathering registries...` issue, can you please send me new logs @tborychowski related to that, to see what's happening before and after that log line since my new builds?

**Comment by tborychowski** [comment] 2024-05-09 17:44
Hi @WarningImHack3r,

Thanks for the update.
Unfortunately I still see the "Gathering registries..." hanging.
I also noticed that the context menu on `package.json` always has all options disabled:
![2024-05-09 at 18 41 39](https://github.com/WarningImHack3r/npm-update-dependencies/assets/392513/5019c299-845e-41bd-b4f4-6a8395a98a1d)

Anyways, here's the longer log of the last beta2: [idea.log](https://github.com/WarningImHack3r/npm-update-dependencies/files/15265761/idea.log)

From the log (and I'm far from expert on jetbrains plugins dev) it looks like it goes into a loop and re-checks all packages over and over, which maybe the reason why the widget doesn't change?

**Comment by WarningImHack3r** [comment] 2024-05-09 18:14
Thanks! I'll investigate further.

Also, yes actions are disabled when they're not available, and as the scans are not done yet then they don't show up as available :)

> (Note: The debug action you see has been enabled from the `Help > Diagnostic Tools > Debug Log Settings…` menu option I made you activate, I highly suggest you disable that once this issue is resolved, not only to hide this action but for performance reasons since your IDE now produces all the heavy debug logs!)

**Comment by WarningImHack3r** [comment] 2024-05-09 20:35
@tborychowski I really didn't see any issue in the full logs you provided: registries are scanned but fail so get skipped, deprecations are scanned, updates too, both again because IntelliJ, the cache is hit whenever possible, no updates or deprecations are found, everything runs fine...

The only issue is those `npm` commands failing but apart from that nothing's wrong... It looks like the status bar is out of sync with the plugin, but the logs say otherwise soooo I don't know, unfortunately...

Last resort: try sending me your `package.json` dependencies so I can paste them into my testing project to see if I can get some issues but I have low hopes :(

**Comment by tborychowski** [comment] 2024-05-09 22:30
I don't think it's package-specific. For fun I created a new project with just the below, and the same issue occurs. It must be something specific to my env, setup or sth like that.

```json
{
  "name": "eslint",
  "version": "1.0.0",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@eslint/js": "^9.2.0",
    "eslint": "^9.2.0",
    "globals": "^15.2.0"
  }
}
```

Anyway, another test that I've done is - I downloaded the previous version of your plugin (2.2.1) and it works great :-)
Log is quite similar to this one (including npm errors) but the widget works fine there.


Re: eslint - it doesn't seem so. I just run the cmd from their get started - `https://eslint.org/docs/latest/use/getting-started` it installs both `eslint` and `@eslint/js`. The latter is used for its `pluginJs.configs.recommended` rule sets.

Re: svelte - thanks, that's very kind of you :-)

**Comment by WarningImHack3r** [comment] 2024-05-10 08:19
Okay, thanks for all that research! I’m gonna try to take another look at the diff between 2.2.1 and 2.3.0, but other than that I don’t know :(

**Comment by WarningImHack3r** [comment] 2024-05-10 10:13
Ok @tborychowski it would be CRAZY if this one actually fixes it, but can you try it? [npm-update-dependencies-2.3.1-beta.3.zip](https://github.com/WarningImHack3r/npm-update-dependencies/files/15273580/npm-update-dependencies-2.3.1-beta.3.zip)

**Comment by tborychowski** [comment] 2024-05-10 10:55
Thanks! That works great!

**Comment by WarningImHack3r** [comment] 2024-05-10 11:36
This one works?? No way

**Comment by WarningImHack3r** [comment] 2024-05-10 12:41
Closing now that it's done, thank you @tborychowski!! Pushing 2.3.1

**Closed by WarningImHack3r** 2024-05-10 12:41 UTC
Labels: bug

**Comment by tborychowski** [comment] 2024-05-10 14:06
Thanks! will do!
