### ISSUE TITLE
"Gathering registries..." hangs in WebStorm 2024.2.3

### ISSUE THREAD

**Issue by Tsyklop** [WarningImHack3r/npm-update-dependencies#146] opened 2024-10-04 14:56 UTC
### What is the issue?

Status hangs in WebStorm 2024.2.3:

![image](https://github.com/user-attachments/assets/82573f27-03c0-4bbe-a509-90e5f39b47ae)

I checked all my projects in Web Storm: NPM updater is not working in all of them.

With IDEA 2024.2.3 all is fine.

### What are the steps to reproduce this issue?

Open `package,json` in WebStorm 2024.2.3.

### What were you expecting to happen?

Updating versions of my dependencies.

### Paste any relevant logs, error output, etc.

```shell
Where I can them?
```

### What OS are you experiencing the problem on?

Windows

### Additional platform information

WebStorm 2024.2.3

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment] 2024-10-04 15:31
Hi there, it looks similar to #102, can you run the `npm config ls` and tell me what happens? Can you also enable debug logs and send them here so I can take a look, as I described at the beginning of this issue?

**Comment by WarningImHack3r** [comment] 2024-10-04 15:55
> Need to paste here?

No that's fine!

> Logs: [idea.log](https://github.com/user-attachments/files/17260883/idea.log)

Thanks, will take a look in less than an hour

**Comment by WarningImHack3r** [comment] 2024-10-04 17:05
@Tsyklop can you locally run the commands `cmd /c npm ls --json` and/or `npm ls --json` and tell me if they work? What happens? (the plugin is stuck waiting for the result of the first one)

**Comment by WarningImHack3r** [comment] 2024-10-04 17:39
Yeah in the same project you're running the extension on
If it works fine, can you enable debug logs (see my second comment on the other issue)?

**Comment by WarningImHack3r** [comment] 2024-10-05 14:22
Unfortunately, this taught me nothing more, the plugin just hangs forever, waiting for the command to finish, but it never does.
I could add a timeout to the command execution, but such a value is very subjective (one system can take way more time than another). Even if I did, the plugin would just be missing some critical info to proceed with its job, so it'd not be really useful at all.

You said that it worked on some projects but not this one, can you send me your `package.json` on that not working project so I can try it on my side?

**Comment by WarningImHack3r** [comment] 2024-10-05 14:45
Hmmm, it's very weird: the IDE doesn't matter for the plugin, only the OS does. There’s nothing IDE-related or version-related...
Are they running on the same machine/OS? Is the version of the IDE the same for both? Same for the plugin version?

If the answer is yes for everything, I'd really love (it's tedious, I know) for you to try downgrading the plugin until it works again, so I can try to figure out what went wrong...

**Comment by trotne** [comment] 2024-10-07 12:10
Hello. I have a similar problem in PHPStorm 2024.1. It works with version v3.1.0, all subsequent versions do not work and give "Gathering registires..."

**Comment by WarningImHack3r** [comment] 2024-10-07 12:37
@Tsyklop can you confirm 3.1.0 was the last "working" version for you as @trotne states?

**Comment by WarningImHack3r** [comment] 2024-10-07 12:44
Alright thanks to both of you, I'll take a look (despite all this making no sense whatsoever)

**Comment by WarningImHack3r** [comment] 2024-10-07 22:00
@Tsyklop @trotne good (bad?) news: I'm able to reproduce the issue on my Windows machine on the latest WS! I'll now investigate and try fixing the issue

**Comment by WarningImHack3r** [comment] 2024-10-08 20:19
@Tsyklop @trotne @IvanSavoskin (you seem to have the same issue Ivan) can you try this build? It fixes it on my development IJ IDE on Windows [npm-update-dependencies-3.4.0-SNAPSHOT.zip](https://github.com/user-attachments/files/17298852/npm-update-dependencies-3.4.0-SNAPSHOT.zip)

**Comment by IvanSavoskin** [comment] 2024-10-08 20:24
Hi! @WarningImHack3r
Yes, I have a similar problem. I installed the plugin from the archive, there is no more eternal loading, but the plugin still does not seem to work. It does not show updates, I want to know for sure that 3 dependencies do not have the latest version now

**Comment by WarningImHack3r** [comment] 2024-10-08 20:27
> I installed the plugin from the archive, there is no more eternal loading

Good to know!

> It does not show updates, I want to know for sure that 3 dependencies do not have the latest version now

What does that mean precisely? That the process ends gracefully but that no updates are reported? Was it showing a different result on previous versions with the exact same conditions?

**Comment by IvanSavoskin** [comment] 2024-10-08 20:31
@WarningImHack3r 

>  That the process ends gracefully but that no updates are reported?

Yes, that's right. The "Gathering registries..." status disappears, but dependencies are not marked in package.json.
This used to happen before. And of course it would go away after a while. Maybe this time too

For more information
I have Windows 11 23H2 (22631.4169) installed
The plugin is installed in IntelliJ IDEA 2024.2.3 (Build #IU-242.23339.11, built on September 25, 2024)
The problems also started after version 3.1.0, everything worked fine on it before

**Comment by IvanSavoskin** [comment] 2024-10-08 20:39
@WarningImHack3r 
I checked the log
Here is an example for two dependencies that definitely has an update

```
2024-10-08 23:36:17,238 [ 15592] INFO - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.checkers.PackageUpdateChecker - Checking for updates for @typescript-eslint/eslint-plugin with comparator 7.18.0
2024-10-08 23:36:17,239 [ 15593] WARN - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.checkers.PackageUpdateChecker - Comparator 7.18.0 is not upgradable

2024-10-08 23:36:17,238 [  15592]   INFO - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.checkers.PackageUpdateChecker - Checking for updates for eslint with comparator 8.57.0
2024-10-08 23:36:17,238 [  15592]   WARN - #com.github.warningimhack3r.npmupdatedependencies.backend.engine.checkers.PackageUpdateChecker - Comparator 8.57.0 is not upgradable
```

**Comment by WarningImHack3r** [comment] 2024-10-08 20:42
Okay if it's only that: technically yes, they can be updated. However, your comparator is a strict version comparator, you don't allow any updates to come through.

Try prefixing your comparators with `^` or `~` or any other to see the plugin suggest you to upgrade.

**Comment by IvanSavoskin** [comment] 2024-10-08 20:44
Strange. This used to work even with a strict comparator. The plugin simply wrote that there was a newer version to update to.

**Comment by WarningImHack3r** [comment] 2024-10-08 20:59
I overhauled the comparator upgradability system in 3.1.0 (last item of its changelog), but I don’t remember it was flawed that much that it was allowing static versions to be upgraded though.

Anyways, don’t hesitate to open another issue if you feel something else is wrong! :)

**Comment by WarningImHack3r** [comment] 2024-10-08 21:00
@Tsyklop @trotne waiting for (one of?) your feedback to push the fix, it’ll be included in 3.4.0 which should be released in the next few weeks.

**Comment by IvanSavoskin** [comment] 2024-10-08 21:10
@WarningImHack3r Now I decided to double check
I installed version 3.0.2. It had the following behavior
<img width="512" alt="Screenshot_1" src="https://github.com/user-attachments/assets/3e94dcb2-0725-451e-8931-b16c5bd35faa">

How valid would it be to open an issue to add this behavior to new versions?
Because it was very convenient and that's exactly why I installed this extension in the first place, since I prefer strict versions

**Comment by trotne** [comment] 2024-10-08 21:12
> @Tsyklop @trotne waiting for (one of?) your feedback to push the fix, it’ll be included in 3.4.0 which should be released in the next few weeks.

I installed your version 3.4.0. Everything works for me with this version. Thank you

**Comment by WarningImHack3r** [comment] 2024-10-08 21:18
> How valid would it be to open an issue to add this behavior to new versions?

You can if you want, but there are almost no chance I do actually add it back.

> Because it was very convenient and that's exactly why I installed this extension in the first place, since I prefer strict versions

Why do you "prefer" strict versions? Why do you if you're still interested in updates?

I follow NPM conventions, strict versions mean "I want this version and this version only, I don't have the intention of updating". If you do want updates, change you comparator: the version won't change unless you change it, and you'll have the benefit of being informed about new updates.

**Comment by IvanSavoskin** [comment] 2024-10-08 21:24
> You can if you want, but there are almost no chance I do actually add it back.

I understand. It seems I'll have to look for some analogue or stay on version 3.0.2 while it works

> Why do you "prefer" strict versions? Why do you if you're still interested in updates?

I prefer to use strict versions to control when exactly and which dependencies to update. Again, some library authors do not always use semantic versioning correctly and can make some cardinal changes to minor versions. Therefore, I feel more comfortable updating dependencies myself, having reviewed the list of changes before doing so

**Comment by WarningImHack3r** [comment] 2024-10-08 21:51
@IvanSavoskin can you please open another issue? I need to think about this more

**Comment by IvanSavoskin** [comment] 2024-10-08 22:03
@WarningImHack3r Thanks!
I created issue https://github.com/WarningImHack3r/npm-update-dependencies/issues/148. Maybe you will find this useful and implement it in one of the future versions.

**Closed** 2024-10-08 22:10 UTC
Labels: bug
