### ISSUE TITLE
[crash] ExternalToolPass:

### ISSUE THREAD

**Issue by pabloalmunia** [WarningImHack3r/npm-update-dependencies#141] opened 2024-10-01 12:42 UTC
### What is the issue?

Crash

### What are the steps to reproduce this issue?

Nothing special,

### What were you expecting to happen?

No error

### Paste any relevant logs, error output, etc.

```shell
com.intellij.diagnostic.PluginException: annotator: com.github.warningimhack3r.npmupdatedependencies.ui.annotation.PackageManagerAnnotator@288abed (class com.github.warningimhack3r.npmupdatedependencies.ui.annotation.PackageManagerAnnotator) [Plugin: com.github.warningimhack3r.npmupdatedependencies]
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.PackageManagerAnnotator.collectInformation(PackageManagerAnnotator.kt:147)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.PackageManagerAnnotator.collectInformation(PackageManagerAnnotator.kt:27)
	... 27 more
```

### What OS are you experiencing the problem on?

Windows

### Additional platform information

Build version: WebStorm 2024.2.3 Build: #WS-242.23339.15 September 25, 2024
JRE: 21.0.4+13-b509.17, JetBrains s.r.o.
JVM: 21.0.4+13-b509.17, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [Developer Tools (5.1.0), Space (242.23339.11), NPM Update Dependencies (3.2.0), Mermaid (0.0.22+IJ.232), SimpleSqliteBrowser (1.0.7), JetBrains AI Assistant (242.23339.11), Grazie Pro (0.3.336), PlantUML Integration (7.11.2-IJ2023.2), MetricsReloaded (1.12), SonarLint (10.10.0.79575), .ignore (4.5.3)]
Disabled plugins:[Conventional Commit (0.23.1), npm-dependency-checker (0.0.3), Database Tools and SQL for WebStorm & RustRover (242.20224.426), JSON to Schema (1.1)]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment] 2024-10-01 14:31
duplicate of #139

**Closed by WarningImHack3r** 2024-10-01 14:31 UTC
Labels: bug
