### ISSUE TITLE
issues with eslint

### ISSUE THREAD

**Issue by Coobaha** [WarningImHack3r/npm-update-dependencies#6] opened 2023-03-27 10:57 UTC
Hey, thanks for your work on this plugin!

I think some missuse of IntelliJ SDK and the plugin completely disables eslint / tsc and probably other services that contribute to JS Quality service.

If I disable `npm-update-dependencies` from the plugin list I am getting eslint/tsc errors reported again

```
IntelliJ IDEA 2023.1 RC (Ultimate Edition)
Build #IU-231.8109.144, built on March 23, 2023
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Kotlin: 231-1.8.20-IJ8109.144
```

**Comment by WarningImHack3r** [comment] 2023-03-28 22:43
Hi! Thanks for reporting the issue. Can you describe more precisely what happens and how I can try to reproduce the problem?
The plugin is only activated in `package.json`, so I don't understand how it could act on anything else, especially such specific language services.
Maybe you are confusing this problem with the "transitional" state between the update of a dependency and the `npm install`.

**Comment by Coobaha** [comment] 2023-03-29 04:35
@WarningImHack3r Yeap, I understand that it should only be activated in `package.json,` but for some reason, I disabled all Problems reported by eslint and others in files. I did a binary search to find this by disabling all plugins and enabling some of them to see the cause. Please note that this might be only a regression in 2023.1. 

- disable plugin
- restart IDE
- setup eslint in the project
- verify that errors are highlighted in files
- enable plugin
- observe that there are no more errors

**Comment by WarningImHack3r** [comment] 2023-03-29 08:06
Did you update to 2023.1 release?
It'd be great if you could send me a minimal setup of your project I can use to try to replicate this issue on my side if the 2023.1 release didn't fix it. I really can't figure out why it would cause such interaction with ESLint.

**Comment by WarningImHack3r** [comment] 2023-04-10 09:37
Closing the issue as it's not reproducible and as I have no other report about a similar issue.

**Comment by Coobaha** [comment] 2023-04-11 04:16
Sorry missed notifications! @WarningImHack3r 
Here is a minimal repro https://gist.github.com/Coobaha/c1a471f095b6cd3470338c920857edee (basically anything)

I am not sure what exactly causes it; it might be that first, you need to open some existing project that will set some state or cause an error.
In the video, you can notice that as I disable the plugin - eslint diagnostics appear.

https://user-images.githubusercontent.com/2446638/231054560-d691acc3-4068-4e47-95ca-7118d180a4cf.mp4

**Comment by WarningImHack3r** [comment] 2023-04-11 18:10
Bug successfully spotted and squashed! The fix will be included in the next (huge) update 🚀

<details>
    <summary>(Weird) cause and fix</summary>
    The bug is due to my <a href="https://github.com/WarningImHack3r/npm-update-dependencies/blob/main/src/main/kotlin/com/github/warningimhack3r/npmupdatedependencies/ui/annotation/AnnotatorsFilter.kt"><code>AnnotatorsFilter</code></a> blocking ESLint annotator for some reason.<br>
    I reworked the logic to allow all annotators in a non-<code>package.json</code> file. I don't wanna remove this class as it's the cleanest way to prevent an annotator to run in every single file...<br>
Anyway, I originally thought this kind of filtering class was only applying to the plugin's scope, I'd never thought it could interfere with other stuff! This is likely a bug though, as neither the <a href="https://plugins.jetbrains.com/docs/intellij/syntax-highlighting-and-error-highlighting.html#external-tool">docs</a> nor the <a href="https://github.com/JetBrains/intellij-community/blob/master/platform/analysis-api/src/com/intellij/lang/ExternalAnnotatorsFilter.java">implementation</a> mention this kind of thing. I'm going to report that to JetBrains and see what they tell me. I'll update this message once I got an answer.
</details>

**Closed** 2023-04-23 16:22 UTC
Labels: bug
