### ISSUE TITLE
[crash] ExternalToolPass:

### ISSUE THREAD

**Issue by eboye** [WarningImHack3r/npm-update-dependencies#142] opened 2024-10-01 18:15 UTC
### What is the issue?

After update to latest version the plugin does not work

### What are the steps to reproduce this issue?

Opened package.json

### What were you expecting to happen?

not to throw an error

### What OS are you experiencing the problem on?

Linux

### Additional platform information

Build version: PhpStorm 2024.2.3 Build: #PS-242.23339.16 September 25, 2024
JRE: 21.0.4+13-b509.17, JetBrains s.r.o.
JVM: 21.0.4+13-b509.17, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 6.11.1-arch1-1 (amd64)

=== Plugins ===
Custom plugins: [CarbonNowSh (1.0.1), Atom One Theme (1.5.1), Toml (242.20224.155), Carbon (3.0.0), NPM Update Dependencies (3.2.0), Tailwind Formatter (2.0.11), Wavefront OBJ (1.4.6), Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.20.2), Properties (242.20224.155), Base64 image encoder (1.2), GitHub Dark Theme (1.1.3), WakaTime (15.0.3), Test Automation (242.22855.133), Grep Console (13.1.0-IJ2023.3), Browserslist (1.0.2), Fast Tools (1.1.5), Vite Integrated (0.2.2), Handlebars/Mustache (242.21829.3), Cypress Support (1.6.2), Solidity (2.4.5), Import Cost (1.4.242), IntelliVue (1.2.16), MDX (242.20224.159), Rainbow Brackets Lite - Free and OpenSource (1.2.0), MJML Support (3.6.0), .env files support (2024.2.1), Laravel Tinker (2.7.3), Laravel Idea (8.3.3.242), GitLive (18.0.0), GitToolBox (600.0.1+242), .ignore (4.5.3)]
Disabled plugins:[Angular (242.23339.16), Codeception Framework (242.23339.16), One Dark Native (1.5), React (242.23339.16), Polymer & Web Components (242.23339.16), Stylus (242.20224.155), ConsoleLogger (0.0.28), Dev Containers (242.23339.16), Subversion (242.23339.16), Slint (1.0.2), Code With Me (242.23339.16), Perforce Helix Core (242.23339.16), Diagrams (242.23339.16), Eclipse Keymap (242.23339.16), Pest (242.23339.16), NetBeans Keymap (242.23339.16), Vagrant (242.23339.16), scss-lint (2.1.1), Mercurial (242.23339.16), One Dark Darker (1.3.8), Space (242.23339.11), Joomla! (242.23339.16), Karma (242.23339.16), GLSL Support (1.24), Truffle (1.1.27), VSCode Keymap (242.23339.16), Machine Learning in Search Everywhere (242.23339.16), GraphQL (242.21829.3), i18n Ally (1.4.2.1), Machine Learning Code Completion (242.23339.16), DQL (242.23339.16), Next.js (242.23339.16), Drupal (242.23339.16), Hunspell (242.23339.16), Visual Studio Keymap (242.23339.16), Cucumber.js (242.23339.16), Inertia.js Support (0.1.8), Behat Support (242.23339.16), Full Line Code Completion (242.23339.16), Phing (242.23339.16), Nuxt.js (2.0.10)]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment] 2024-10-01 18:47
Hi, can I have more information about the crash? Are you sure it's not a duplicate of #139?

**Comment by WarningImHack3r** [comment] 2024-10-01 21:22
If it’s not or if 3.2.1 doesn’t fix it, please reopen the issue with additional information

**Comment by eboye** [comment] 2024-10-01 22:31
Yup, 3.2.1 fixed it, so I suppose it is a duplicate after all. Thanks!

**Comment by WarningImHack3r** [comment] 2024-10-02 05:13
Duplicate of #139

**Closed by WarningImHack3r** 2024-10-02 05:13 UTC
Labels: bug
